version: '3.8'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 193566
      POSTGRES_DB: authdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d 

  web:
    build: .
    ports:
      - "4444:4444"
    environment:
      DATABASE_URL: postgres://postgres:193566@db:5432/authdb?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /Users/vyacheslavivkin/Desktop/dev/go/AuthDB/db.env:/app/db.env