FROM golang:1.22 as test
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . ./
COPY db.env /app/db.env
# Setting environment variables from db.env
ENV $(cat /app/db.env | xargs)

# RUN apt-get update && apt-get install -y dockerize


ENV $(cat /app/db.env | xargs)
ENV DB_HOST=testdb
ENV DB_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=193566
ENV DB_NAME=testdb
    

CMD ["go", "test", "-timeout", "30s", "./..."]
# CMD ["dockerize", "-wait", "tcp://testdb:5432", "-timeout", "90s", "go", "test", "-timeout", "60s", "./..."]

