name: Go

on:
  push:
    branches: 
      - "main"
      - "tomerge"
  pull_request:
    branches: 
      - "main"
      - "tomerge"

jobs:

  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest] 
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install docker-compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Check Dockerfile and Compose
      run: |
        ls -la
        cat Dockerfile
        cat compose.yaml

    - name: Build and Run Tests in Docker
      run: |
        docker-compose -f compose.yaml up -d maindb testdb
        docker-compose run test go test -v ./...
        docker-compose down

  docker:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: vzikass/authdb:latest